### PR TITLE
add span attributes to frontend

### PR DESCRIPTION
**Pull request by puckpuck**
Updates #49 to add new attributes to existing spans.

## Changes

Adds attributes to frontend service spans
All handlers are wrapped with common attributes (session, request, currency, user). 
Most handlers have application-specific attributes added
Defines an `instr` package that contains some semantic conventions

* [x] Appropriate `CHANGELOG.md` updated for non-trivial changes
* [x] Design discussion issue #42  and #49 

This adds some conventions (ie: `app.` prefix) to attribute names.  We should settle on clean conventions before pushing similar instrumentation to other services.

### CODE REVIEW

**Comment by cartersocha** [comment]
When I run your branch the spans look the same as the current version. Could you post a screenshot of your output?

**Comment by cartersocha** [comment]
Thanks for the pic. I was checking for attributes but had been glancing through the console output which doesn't have them for whatever reason. 

LGTM

**Review by cartersocha — APPROVED** [review]

**Comment by cartersocha** [comment]
Are you planning on documenting this in the service readme?

**Comment by puckpuck** [comment]
> Are you planning on documenting this in the service readme?

That's the new PR ;)

**Comment by puckpuck** [comment]
> Are you planning on documenting this in the service readme?

That's the next PR 😉

**Pull request merged**
