### PR TITLE
[docs] move Requirements to docs/requirements

### PR DESCRIPTION
**Pull request by wph95**
1. move Requirements to the docs folder
2. refer to otel/spec, folder/file names follow UnderScoreCase)

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
CI caught some additional links that need to be updated.

**Comment by wph95** [comment]
> CI caught some additional links that need to be updated.

yep, I saw it, is working to fix it :)

**Review by cartersocha — APPROVED** [review]
LGTM

**Comment by cartersocha** [comment]
Thanks for doing this @wph95. Slightly related I noticed the broken links check is still showing up capitalized. Is that a cache issue on my side? I thought you changed it in the original pr

**Comment by wph95** [comment]
> Thanks for doing this @wph95. Slightly related I noticed the broken links check is still showing up capitalized. Is that a cache issue on my side? I thought you changed it in the original pr

@cartersocha I think the last commit  `c176cdb` is fixed broken links, and all ci is pass

**Pull request merged**
