### PR TITLE
Update Dockerfile for currencyservice

### PR DESCRIPTION
**Pull request by Umleitungen**
Fixes #.

## Changes

Please provide a brief description of the changes here.

to build it succesfully, these two package should be installed : libcurl4-openssl-dev and nlohmann-json3-dev

### CODE REVIEW

**Comment by cartersocha** [comment]
Hey @Umleitungen is this related to a bug you found? What drove the PR fix?

**Comment by Umleitungen** [comment]
@cartersocha , I created and linked two issues, please review

**Comment by cartersocha** [comment]
Ty. 

@lalitb, @DebajitDas seems we have 2 potential currency service bugs. Could you please take a look?

**Comment by cartersocha** [comment]
Issues 208 & 209 are related to this

**Review by lalitb — APPROVED** [review]

**Comment by lalitb** [comment]
> @lalitb, @DebajitDas seems we have 2 potential currency service bugs. Could you please take a look?

Looks good to me. Thanks for the fix.

**Review by julianocosta89 — APPROVED** [review]

**Comment by reyang** [comment]
@Umleitungen would you clear the EasyCLA? Thanks!

**Review by DebajitDas — APPROVED** [review]
lgtm

**Review by wph95 — APPROVED** [review]
LGTM

**Comment by cartersocha** [comment]
Closing this. I opened a pr with your updates so we could get the fix out asap. Thanks for contributing @Umleitungen. Make sure to sign the cla when you get a chance!

**Comment by Umleitungen** [comment]
@cartersocha  sure, I am glad it helps

**Pull request closed without merging**
