### PR TITLE
Fixing an emailservice build problem.

### PR DESCRIPTION
**Pull request by mviitane**
Fixing an emailservice build problem.

The build is currently failing when running
`docker-compose up`

Problem:
`Step 3/8 : COPY Gemfile* .
When using COPY with more than one source file, the destination must be a directory and end with a /
ERROR: Service 'emailservice' failed to build : Build failed`

## Changes

Dockerfile updated to fix the build.

### CODE REVIEW

**Comment by cartersocha** [comment]
Just read through the docker files and this does look like a bug

**Review by cartersocha — APPROVED** [review]

**Comment by cartersocha** [comment]
Thanks for verifying this @proffalken. Just merged the fix

**Comment by ahayworth** [comment]
Huh - thanks for fixing everyone. Never saw this on my machine when implementing it, but I suppose that's why "works on my machine" is dangerous. 😄 ❤️

**Pull request merged**
