### PR TITLE
Add list of all manual attributes

### PR DESCRIPTION
**Pull request by julianocosta89**
With all the services being instrumented manually, it would be great if we could keep the span attributes documented.
I've went through all services and the opened PRs to create the initial  file.
From this, we can keep it updated whenever new PRs arrive, and we can follow a naming convention across all services.

### CODE REVIEW

**Comment by cartersocha** [comment]
Lgtm. Thanks for doing this

**Review by cartersocha — APPROVED** [review]
We could put these in the individual service readmes too but I see a benefit in centralizing too. It’s easy to go either way here.  

Centralizing makes sense for now to me. I’d prefer to check one doc than 11 readmes personally

**Comment by julianocosta89** [comment]
> Centralizing makes sense for now to me. I’d prefer to check one doc than 11 readmes personally

Me too 😅

**Comment by cartersocha** [comment]
Should we shift the generic feature tables to separate centralized docs too? Align it by traces, metrics, logs? Then just update in one place

**Comment by julianocosta89** [comment]
Which generic feature tables?

**Comment by austinlparker** [comment]
We can work on consolidating more in a separate PR -- this seems good to go, merging.

**Pull request merged**
