### PR TITLE
Add default server port constant

### PR DESCRIPTION
**Pull request by laziobird**
## Changes

A port constant is defined in one place and is used anywhere .

### CODE REVIEW

**Comment by mic-max** [comment]
I feel like each service requiring an environment variable before running would be okay for this demo. So if it's not present I think crashing early instead of even trying to use a default port number would be better since the port number `9555` in this service's case is also defined in the `compose.yml` and the frontend which `depends_on` this service being present at the address:port defined in the `.env` file is not found but the `adservice` is running, just on a different port, could cause confusion.

My idea:

Define all addresses in the `.env` file. If a service can't load it's port or another service it depends on from the environment variables then the program should exit with and error.

**Comment by laziobird** [comment]
Thanks for so good suggestions and notices !   @reyang  @mic-max   .

**Comment by cartersocha** [comment]
LGTM. @mic-max, @reyang, any further suggestions or comments?

**Comment by mic-max** [comment]
> LGTM. @mic-max, @reyang, any further suggestions or comments?

I prefer the environment variable only approach instead of this

**Comment by reyang** [comment]
> > LGTM. @mic-max, @reyang, any further suggestions or comments?
> 
> I prefer the environment variable only approach instead of this

+1

**Comment by laziobird** [comment]
> > > LGTM. @mic-max, @reyang, any further suggestions or comments?
> > 
> > 
> > I prefer the environment variable only approach instead of this
> 
> +1

OK，i can add this environment variable tomorrow ☺

**Pull request closed without merging**
