### PR TITLE
removed capitalized name for broken link checker

### PR DESCRIPTION
**Pull request by cartersocha**
FYI @wph95 I think removing the name should fix the capitalization

### CODE REVIEW

**Review by wph95 — APPROVED** [review]
LGTM

**Comment by cartersocha** [comment]
It seems it is expecting Broken Links but I removed the reference so it is breaking. @reyang, @wph95 any suggestions? Is this a repo or code issue?

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
> It seems it is expecting Broken Links but I removed the reference so it is breaking. @reyang, @wph95 any suggestions? Is this a repo or code issue?

I've made the config change.

It's configured at repo/branch level https://github.com/open-telemetry/opentelemetry-demo-webstore/settings/branch_protection_rules/25424445:

image

**Comment by cartersocha** [comment]
Thanks I figured it was something like that. I'll start there next time

**Pull request merged**
