### PR TITLE
push image to dockerhub

### LINKED ISSUE #78: Setup CI workflow to Docker Hub
The most recent build of the community demo should be available for download on Docker Hub & have automated deployment from the repo. 

The community demo should be posted by the community "[otel](https://hub.docker.com/u/otel)" user on the docker hub. 

 

- [x] Define image_name image_tag format
- [x]  Setup CI workflow to build the image
- [x]  Setup CI workflow to push image to GitHub package (via GitHub action)
- [ ]  docker hub credentials
- [ ]  push image to docker hub (via GitHub action)

### PR DESCRIPTION
**Pull request by wph95**
fix #78 
github action add push docker image to dockerhub

### CODE REVIEW

**Review by julianocosta89 — COMMENTED** [review]
Hello @wph95 👋🏽 

Shouldn't we use the OTel registry now?
The image names used in the file are:
- ghcr.io/wph95/demo
- otelbot/demo

Is that correct?

**Comment by wph95** [comment]
> Hello @wph95 👋🏽
> 
> Shouldn't we use the OTel registry now? The image names used in the file are:
> 
> * ghcr.io/wph95/demo
> * otelbot/demo
> 
> Is that correct?

fixed it

https://github.com/open-telemetry/community/blob/main/assets.md#docker-hub
our dockerhub account is "otelbot"

> * ghcr.io/wph95/demo
> * otelbot/demo

**Review by julianocosta89 — COMMENTED** [review]
LGTM!

**Review by julianocosta89 — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Comment by cartersocha** [comment]
Thanks @wph95!

**Pull request merged**
