### PR TITLE
enhance productcatalogservice tracing support: add attributes to existing spans

### LINKED ISSUE #50: Review and enhance tracing support for product catalog service (Go)
The following is a list of requirements that we need to evaluate before declaring v1 for trace telemetry. These requirements are across the entire application; Not all services will meet all requirements. Determine the relevant features for this service. 

- [ ] Automatic Instrumentation is being used where appropriate.
- [ ] Library instrumentation is being used if automatic instrumentation is unavailable.
- [x] Services extend automatic instrumentation.
  - [x] New attributes/events attached to existing spans.
  - [ ] New spans are being created from existing spans.
- [ ] Automatic and Manual Context Propagation are being demonstrated.
- [ ] Telemetry is not being sampled upfront.
- [ ] Telemetry is not being filtered upfront.
- [ ] Baggage is being set and read appropriately (i.e., baggage must be explicitly set as attributes on spans)
- [ ] Update the [centralized tracing doc](https://github.com/open-telemetry/opentelemetry-demo/blob/main/docs/trace_service_features.md)
Referencing: https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/42

Service: https://github.com/open-telemetry/opentelemetry-demo-webstore/blob/main/src/productcatalogservice/README.md

### PR DESCRIPTION
**Pull request by fatsheep9146**
fix #50 

I'm trying to fix 

- [ ] Services extend automatic instrumentation.
  - [ ]  New attributes/events attached to existing spans.

Changes

Adds attributes to existing span in GetProduct handler.

### CODE REVIEW

**Comment by fatsheep9146** [comment]
The screen shot is like following

image

**Review by julianocosta89 — CHANGES_REQUESTED** [review]
Hello @fatsheep9146, could you add some extra attributes?
And also some events?

**Comment by puckpuck** [comment]
I'd like to see the ListProducts and SearchProducts handlers with additional attributes as well.  We can add the total products returned to both, and the search query to the latter.

**Comment by fatsheep9146** [comment]
ping @puckpuck @julianocosta89 for review. I've added more attributes and events. Please help to review this, thanks :)

**Review by julianocosta89 — APPROVED** [review]
LGTM! 🤩

**Comment by cartersocha** [comment]
@fatsheep9146 please update the issue to reflect your changes. 

Merging now 🦑

**Comment by fatsheep9146** [comment]
> Contributor

@cartersocha I saw that you closed the issue #50. I think the issue is not ready to be closed, there are still several features needed to be resolved.

**Comment by fatsheep9146** [comment]
> @fatsheep9146 please update the issue to reflect your changes.
> 
> Merging now 🦑

@cartersocha I saw that you closed the issue https://github.com/open-telemetry/opentelemetry-demo-webstore/issues/50. I think the issue is not ready to be closed, there are still several features needed to be resolved.

**Comment by cartersocha** [comment]
I think the merge automatically closed the issue. I just re-opened it. I agree it’s not done yet! 🧜🏻‍♂️

**Pull request merged**
